In [1]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

In [3]:
arr1 = np.arange(9).reshape(3,3)

In [4]:
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [5]:
np.concatenate([arr1,arr1],axis=1)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

In [6]:
np.concatenate([arr1,arr1],axis=0)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [7]:
ser1 = Series([0,1,2,], index=['T','U','V'])

ser2 = Series([3,4], index=['X','Y'])

In [8]:
ser1

T    0
U    1
V    2
dtype: int64

In [9]:
ser2

X    3
Y    4
dtype: int64

In [10]:
pd.concat([ser1,ser2])

T    0
U    1
V    2
X    3
Y    4
dtype: int64

In [11]:
pd.concat([ser1,ser2],axis=1)

0    1
T  0.0  NaN
U  1.0  NaN
V  2.0  NaN
X  NaN  3.0
Y  NaN  4.0

In [13]:
pd.concat([ser1,ser2],keys=['cat1','cat2'])

cat1  T    0
      U    1
      V    2
cat2  X    3
      Y    4
dtype: int64

In [14]:
dframe1 = DataFrame(np.random.randn(4,3), columns = ['X', 'Y','Z'])
dframe2 = DataFrame(np.random.randn(3,3), columns = ['Y','Q','X'])

In [15]:
dframe1

X         Y         Z
0  0.902538  0.368761 -1.698866
1  1.082716 -0.339876  0.592931
2 -1.309712 -1.210573 -0.644180
3 -0.841376  0.322886  1.991392

In [16]:
dframe2

Y         Q         X
0 -0.611700 -0.386824  0.844202
1 -0.380109 -0.025271 -0.886846
2 -1.929386  0.649097 -1.517045

In [18]:
pd.concat([dframe1, dframe2])

Q         X         Y         Z
0       NaN  0.902538  0.368761 -1.698866
1       NaN  1.082716 -0.339876  0.592931
2       NaN -1.309712 -1.210573 -0.644180
3       NaN -0.841376  0.322886  1.991392
0 -0.386824  0.844202 -0.611700       NaN
1 -0.025271 -0.886846 -0.380109       NaN
2  0.649097 -1.517045 -1.929386       NaN

In [20]:
# 열 reset하고 concat하고 싶을 때
pd.concat([dframe1, dframe2], ignore_index=True)

Q         X         Y         Z
0       NaN  0.902538  0.368761 -1.698866
1       NaN  1.082716 -0.339876  0.592931
2       NaN -1.309712 -1.210573 -0.644180
3       NaN -0.841376  0.322886  1.991392
4 -0.386824  0.844202 -0.611700       NaN
5 -0.025271 -0.886846 -0.380109       NaN
6  0.649097 -1.517045 -1.929386       NaN

In [21]:
url = 'http://pandas.pydata.org/pandas-docs/dev/generated/pandas.tools.merge.concat.hrml'