In [1]:
import numpy as np

In [2]:
arr = np.arange(11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ,
        3.16227766])

In [5]:
np.exp(arr)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03,   2.20264658e+04])

In [6]:
A = np.random.randn(10)

In [7]:
A

array([ 0.75327244,  1.53467777,  0.49162424,  0.66408338, -0.72734107,
        2.14458543,  0.15375863,  0.49460391, -1.02460841,  1.16941137])

In [8]:
A = np.random.randn(10)
A

array([ 1.36385533, -0.41030335,  0.19270873, -0.0039455 ,  2.08199105,
        2.09990045, -0.74768241, -0.20233029,  1.21299638, -1.50530643])

In [9]:
B = np.random.randn(10)
B

array([-0.6591762 ,  1.13042997, -0.00899691, -0.79094857, -0.24021873,
        0.36434796, -0.2139731 , -0.44214506,  0.58020231, -0.35681202])

In [10]:
# Binary Functions
np.add(A,B)

array([ 0.70467913,  0.72012662,  0.18371181, -0.79489407,  1.84177232,
        2.46424841, -0.96165551, -0.64447535,  1.79319869, -1.86211845])

In [11]:
np.maximum(A,B)

array([ 1.36385533,  1.13042997,  0.19270873, -0.0039455 ,  2.08199105,
        2.09990045, -0.2139731 , -0.20233029,  1.21299638, -0.35681202])

In [16]:
website = 'http://docs.scipy.org/doc/numpy/reference/ufuncs.html#available-ufuncs'
import webbrowser
webbrowser.open(website)

True